/* AUTO-GENERATED by tools/migrate/discover.ts — DO NOT EDIT BY HAND.
   Disk-discovery result (which lectures/tests/PDFs exist). Re-run `npm run discover`. */

export type Token = number | string;
export type PdfItem = { token: Token; file: string };
export type SubjectContent = { lecture: Token[]; test: Token[]; pdf: PdfItem[] };
/** key = `${yearId}/${semId}/${subId}` */
export type ContentIndex = Record<string, SubjectContent>;

export const CONTENT_INDEX: ContentIndex = {
  "3rd/s1/ocih": {
    "lecture": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
      "21",
      "22",
      "23",
      "24",
      "25",
      "26",
      "27",
      "28",
      "29",
      "30",
      "31",
      "32",
      "33",
      "34",
      "35",
      "36",
      "37",
      "38",
      "39",
      "40",
      "41"
    ],
    "test": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
      "21",
      "22",
      "23",
      "24",
      "25",
      "26",
      "27",
      "28",
      "29",
      "30",
      "31",
      "32",
      "33",
      "34",
      "35",
      "36",
      "37",
      "38",
      "39",
      "40",
      "41"
    ],
    "pdf": [
      {
        "token": "1",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-1.pdf"
      },
      {
        "token": "2",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-2.pdf"
      },
      {
        "token": "3",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-3.pdf"
      },
      {
        "token": "4",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-4.pdf"
      },
      {
        "token": "5",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-5.pdf"
      },
      {
        "token": "6",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-6.pdf"
      },
      {
        "token": "7",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-7.pdf"
      },
      {
        "token": "8",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-8.pdf"
      },
      {
        "token": "9",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-9.pdf"
      },
      {
        "token": "10",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-10.pdf"
      },
      {
        "token": "11",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-11.pdf"
      },
      {
        "token": "12",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-12.pdf"
      },
      {
        "token": "13",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-13.pdf"
      },
      {
        "token": "14",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-14.pdf"
      },
      {
        "token": "15",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-15.pdf"
      },
      {
        "token": "16",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-16.pdf"
      },
      {
        "token": "17",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-17.pdf"
      },
      {
        "token": "18",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-18.pdf"
      },
      {
        "token": "19",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-19.pdf"
      },
      {
        "token": "20",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-20.pdf"
      },
      {
        "token": "21",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-21.pdf"
      },
      {
        "token": "22",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-22.pdf"
      },
      {
        "token": "23",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-23.pdf"
      },
      {
        "token": "24",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-24.pdf"
      },
      {
        "token": "25",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-25.pdf"
      },
      {
        "token": "26",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-26.pdf"
      },
      {
        "token": "27",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-27.pdf"
      },
      {
        "token": "28",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-28.pdf"
      },
      {
        "token": "29",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-29.pdf"
      },
      {
        "token": "30",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-30.pdf"
      },
      {
        "token": "31",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-31.pdf"
      },
      {
        "token": "32",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-32.pdf"
      },
      {
        "token": "33",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-33.pdf"
      },
      {
        "token": "34",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-34.pdf"
      },
      {
        "token": "35",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-35.pdf"
      },
      {
        "token": "36",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-36.pdf"
      },
      {
        "token": "37",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-37.pdf"
      },
      {
        "token": "38",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-38.pdf"
      },
      {
        "token": "39",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-39.pdf"
      },
      {
        "token": "40",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-40.pdf"
      },
      {
        "token": "41",
        "file": "/3rd-year/3rd-s1/ocih/pdf/ocih-41.pdf"
      }
    ]
  },
  "3rd/s1/radiology": {
    "lecture": [
      "1-2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11"
    ],
    "test": [
      "1-2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11"
    ],
    "pdf": [
      {
        "token": "1-2",
        "file": "/3rd-year/3rd-s1/radiology/pdf/rad-1-2.pdf"
      },
      {
        "token": "3",
        "file": "/3rd-year/3rd-s1/radiology/pdf/rad-3.pdf"
      },
      {
        "token": "4",
        "file": "/3rd-year/3rd-s1/radiology/pdf/rad-4.pdf"
      },
      {
        "token": "5",
        "file": "/3rd-year/3rd-s1/radiology/pdf/rad-5.pdf"
      },
      {
        "token": "6",
        "file": "/3rd-year/3rd-s1/radiology/pdf/rad-6.pdf"
      },
      {
        "token": "7",
        "file": "/3rd-year/3rd-s1/radiology/pdf/rad-7.pdf"
      },
      {
        "token": "8",
        "file": "/3rd-year/3rd-s1/radiology/pdf/rad-8.pdf"
      },
      {
        "token": "9",
        "file": "/3rd-year/3rd-s1/radiology/pdf/rad-9.pdf"
      },
      {
        "token": "10",
        "file": "/3rd-year/3rd-s1/radiology/pdf/rad-10.pdf"
      },
      {
        "token": "11",
        "file": "/3rd-year/3rd-s1/radiology/pdf/rad-11.pdf"
      }
    ]
  },
  "3rd/s1/preclinical": {
    "lecture": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20"
    ],
    "test": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20"
    ],
    "pdf": [
      {
        "token": "1",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-1.pdf"
      },
      {
        "token": "2",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-2.pdf"
      },
      {
        "token": "3",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-3.pdf"
      },
      {
        "token": "4",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-4.pdf"
      },
      {
        "token": "5",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-5.pdf"
      },
      {
        "token": "6",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-6.pdf"
      },
      {
        "token": "7",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-7.pdf"
      },
      {
        "token": "8",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-8.pdf"
      },
      {
        "token": "9",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-9.pdf"
      },
      {
        "token": "10",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-10.pdf"
      },
      {
        "token": "11",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-11.pdf"
      },
      {
        "token": "12",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-12.pdf"
      },
      {
        "token": "13",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-13.pdf"
      },
      {
        "token": "14",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-14.pdf"
      },
      {
        "token": "15",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-15.pdf"
      },
      {
        "token": "16",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-16.pdf"
      },
      {
        "token": "17",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-17.pdf"
      },
      {
        "token": "18",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-18.pdf"
      },
      {
        "token": "19",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-19.pdf"
      },
      {
        "token": "20",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-20.pdf"
      }
    ]
  },
  "3rd/s1/pharmacology": {
    "lecture": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14"
    ],
    "test": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14"
    ],
    "pdf": [
      {
        "token": "1",
        "file": "/3rd-year/3rd-s1/pharmacology/pdf/pharma-1.pdf"
      },
      {
        "token": "2",
        "file": "/3rd-year/3rd-s1/pharmacology/pdf/pharma-2.pdf"
      },
      {
        "token": "3",
        "file": "/3rd-year/3rd-s1/pharmacology/pdf/pharma-3.pdf"
      },
      {
        "token": "4",
        "file": "/3rd-year/3rd-s1/pharmacology/pdf/pharma-4.pdf"
      },
      {
        "token": "5",
        "file": "/3rd-year/3rd-s1/pharmacology/pdf/pharma-5.pdf"
      },
      {
        "token": "6",
        "file": "/3rd-year/3rd-s1/pharmacology/pdf/pharma-6.pdf"
      },
      {
        "token": "7",
        "file": "/3rd-year/3rd-s1/pharmacology/pdf/pharma-7.pdf"
      },
      {
        "token": "8",
        "file": "/3rd-year/3rd-s1/pharmacology/pdf/pharma-8.pdf"
      },
      {
        "token": "9",
        "file": "/3rd-year/3rd-s1/pharmacology/pdf/pharma-9.pdf"
      },
      {
        "token": "10",
        "file": "/3rd-year/3rd-s1/pharmacology/pdf/pharma-10.pdf"
      },
      {
        "token": "11",
        "file": "/3rd-year/3rd-s1/pharmacology/pdf/pharma-11.pdf"
      },
      {
        "token": "12",
        "file": "/3rd-year/3rd-s1/pharmacology/pdf/pharma-12.pdf"
      },
      {
        "token": "13",
        "file": "/3rd-year/3rd-s1/pharmacology/pdf/pharma-13.pdf"
      },
      {
        "token": "14",
        "file": "/3rd-year/3rd-s1/pharmacology/pdf/pharma-14.pdf"
      }
    ]
  },
  "3rd/s1/pathology": {
    "lecture": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11"
    ],
    "test": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11"
    ],
    "pdf": [
      {
        "token": "1",
        "file": "/3rd-year/3rd-s1/pathology/pdf/patho-1.pdf"
      },
      {
        "token": "2",
        "file": "/3rd-year/3rd-s1/pathology/pdf/patho-2.pdf"
      },
      {
        "token": "3",
        "file": "/3rd-year/3rd-s1/pathology/pdf/patho-3.pdf"
      },
      {
        "token": "4",
        "file": "/3rd-year/3rd-s1/pathology/pdf/patho-4.pdf"
      },
      {
        "token": "5",
        "file": "/3rd-year/3rd-s1/pathology/pdf/patho-5.pdf"
      },
      {
        "token": "6",
        "file": "/3rd-year/3rd-s1/pathology/pdf/patho-6.pdf"
      },
      {
        "token": "7",
        "file": "/3rd-year/3rd-s1/pathology/pdf/patho-7.pdf"
      },
      {
        "token": "8",
        "file": "/3rd-year/3rd-s1/pathology/pdf/patho-8.pdf"
      },
      {
        "token": "9",
        "file": "/3rd-year/3rd-s1/pathology/pdf/patho-9.pdf"
      },
      {
        "token": "10",
        "file": "/3rd-year/3rd-s1/pathology/pdf/patho-10.pdf"
      },
      {
        "token": "11",
        "file": "/3rd-year/3rd-s1/pathology/pdf/patho-11.pdf"
      }
    ]
  },
  "3rd/s2/ocd": {
    "lecture": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20"
    ],
    "test": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20"
    ],
    "pdf": [
      {
        "token": "1",
        "file": "/3rd-year/3rd-s2/ocd/pdf/ocd-1.pdf"
      },
      {
        "token": "2",
        "file": "/3rd-year/3rd-s2/ocd/pdf/ocd-2.pdf"
      },
      {
        "token": "3",
        "file": "/3rd-year/3rd-s2/ocd/pdf/ocd-3.pdf"
      },
      {
        "token": "4",
        "file": "/3rd-year/3rd-s2/ocd/pdf/ocd-4.pdf"
      },
      {
        "token": "5",
        "file": "/3rd-year/3rd-s2/ocd/pdf/ocd-5.pdf"
      },
      {
        "token": "6",
        "file": "/3rd-year/3rd-s2/ocd/pdf/ocd-6.pdf"
      },
      {
        "token": "7",
        "file": "/3rd-year/3rd-s2/ocd/pdf/ocd-7.pdf"
      },
      {
        "token": "8",
        "file": "/3rd-year/3rd-s2/ocd/pdf/ocd-8.pdf"
      },
      {
        "token": "9",
        "file": "/3rd-year/3rd-s2/ocd/pdf/ocd-9.pdf"
      },
      {
        "token": "10",
        "file": "/3rd-year/3rd-s2/ocd/pdf/ocd-10.pdf"
      },
      {
        "token": "11",
        "file": "/3rd-year/3rd-s2/ocd/pdf/ocd-11.pdf"
      },
      {
        "token": "12",
        "file": "/3rd-year/3rd-s2/ocd/pdf/ocd-12.pdf"
      },
      {
        "token": "13",
        "file": "/3rd-year/3rd-s2/ocd/pdf/ocd-13.pdf"
      },
      {
        "token": "14",
        "file": "/3rd-year/3rd-s2/ocd/pdf/ocd-14.pdf"
      },
      {
        "token": "15",
        "file": "/3rd-year/3rd-s2/ocd/pdf/ocd-15.pdf"
      },
      {
        "token": "16",
        "file": "/3rd-year/3rd-s2/ocd/pdf/ocd-16.pdf"
      },
      {
        "token": "17",
        "file": "/3rd-year/3rd-s2/ocd/pdf/ocd-17.pdf"
      },
      {
        "token": "18",
        "file": "/3rd-year/3rd-s2/ocd/pdf/ocd-18.pdf"
      },
      {
        "token": "19",
        "file": "/3rd-year/3rd-s2/ocd/pdf/ocd-19.pdf"
      },
      {
        "token": "20",
        "file": "/3rd-year/3rd-s2/ocd/pdf/ocd-20.pdf"
      }
    ]
  },
  "3rd/s2/psychology": {
    "lecture": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10"
    ],
    "test": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10"
    ],
    "pdf": [
      {
        "token": "1",
        "file": "/3rd-year/3rd-s2/psychology/pdf/psychology-1.pdf"
      },
      {
        "token": "2",
        "file": "/3rd-year/3rd-s2/psychology/pdf/psychology-2.pdf"
      },
      {
        "token": "3",
        "file": "/3rd-year/3rd-s2/psychology/pdf/psychology-3.pdf"
      },
      {
        "token": "4",
        "file": "/3rd-year/3rd-s2/psychology/pdf/psychology-4.pdf"
      },
      {
        "token": "5",
        "file": "/3rd-year/3rd-s2/psychology/pdf/psychology-5.pdf"
      },
      {
        "token": "6",
        "file": "/3rd-year/3rd-s2/psychology/pdf/psychology-6.pdf"
      },
      {
        "token": "7",
        "file": "/3rd-year/3rd-s2/psychology/pdf/psychology-7.pdf"
      },
      {
        "token": "8",
        "file": "/3rd-year/3rd-s2/psychology/pdf/psychology-8.pdf"
      },
      {
        "token": "9",
        "file": "/3rd-year/3rd-s2/psychology/pdf/psychology-9.pdf"
      },
      {
        "token": "10",
        "file": "/3rd-year/3rd-s2/psychology/pdf/psychology-10.pdf"
      }
    ]
  },
  "3rd/s2/preclinical": {
    "lecture": [],
    "test": [],
    "pdf": [
      {
        "token": "1",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-1.pdf"
      },
      {
        "token": "2",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-2.pdf"
      },
      {
        "token": "3",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-3.pdf"
      },
      {
        "token": "4",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-4.pdf"
      },
      {
        "token": "5",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-5.pdf"
      },
      {
        "token": "6",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-6.pdf"
      },
      {
        "token": "7",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-7.pdf"
      },
      {
        "token": "8",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-8.pdf"
      },
      {
        "token": "9",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-9.pdf"
      },
      {
        "token": "10",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-10.pdf"
      },
      {
        "token": "11",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-11.pdf"
      },
      {
        "token": "12",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-12.pdf"
      },
      {
        "token": "13",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-13.pdf"
      },
      {
        "token": "14",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-14.pdf"
      },
      {
        "token": "15",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-15.pdf"
      },
      {
        "token": "16",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-16.pdf"
      },
      {
        "token": "17",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-17.pdf"
      },
      {
        "token": "18",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-18.pdf"
      },
      {
        "token": "19",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-19.pdf"
      },
      {
        "token": "20",
        "file": "/3rd-year/3rd-s1/preclinical/pdf/pre-20.pdf"
      }
    ]
  },
  "3rd/s2/elective": {
    "lecture": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9"
    ],
    "test": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9"
    ],
    "pdf": [
      {
        "token": "1",
        "file": "/3rd-year/3rd-s2/elective/pdf/elective-1.pdf"
      },
      {
        "token": "2",
        "file": "/3rd-year/3rd-s2/elective/pdf/elective-2.pdf"
      },
      {
        "token": "3",
        "file": "/3rd-year/3rd-s2/elective/pdf/elective-3.pdf"
      },
      {
        "token": "4",
        "file": "/3rd-year/3rd-s2/elective/pdf/elective-4.pdf"
      },
      {
        "token": "5",
        "file": "/3rd-year/3rd-s2/elective/pdf/elective-5.pdf"
      },
      {
        "token": "6",
        "file": "/3rd-year/3rd-s2/elective/pdf/elective-6.pdf"
      },
      {
        "token": "7",
        "file": "/3rd-year/3rd-s2/elective/pdf/elective-7.pdf"
      },
      {
        "token": "8",
        "file": "/3rd-year/3rd-s2/elective/pdf/elective-8.pdf"
      },
      {
        "token": "9",
        "file": "/3rd-year/3rd-s2/elective/pdf/elective-9.pdf"
      }
    ]
  },
  "3rd/s2/bsd": {
    "lecture": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14"
    ],
    "test": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14"
    ],
    "pdf": [
      {
        "token": "1",
        "file": "/3rd-year/3rd-s2/bsd/pdf/bsd-pdf-1.pdf"
      },
      {
        "token": "2",
        "file": "/3rd-year/3rd-s2/bsd/pdf/bsd-pdf-2.pdf"
      },
      {
        "token": "3",
        "file": "/3rd-year/3rd-s2/bsd/pdf/bsd-pdf-3.pdf"
      },
      {
        "token": "4",
        "file": "/3rd-year/3rd-s2/bsd/pdf/bsd-pdf-4.pdf"
      },
      {
        "token": "5",
        "file": "/3rd-year/3rd-s2/bsd/pdf/bsd-pdf-5.pdf"
      },
      {
        "token": "6",
        "file": "/3rd-year/3rd-s2/bsd/pdf/bsd-pdf-6.pdf"
      },
      {
        "token": "7",
        "file": "/3rd-year/3rd-s2/bsd/pdf/bsd-pdf-7.pdf"
      },
      {
        "token": "8",
        "file": "/3rd-year/3rd-s2/bsd/pdf/bsd-pdf-8.pdf"
      },
      {
        "token": "9",
        "file": "/3rd-year/3rd-s2/bsd/pdf/bsd-pdf-9.pdf"
      },
      {
        "token": "10",
        "file": "/3rd-year/3rd-s2/bsd/pdf/bsd-pdf-10.pdf"
      },
      {
        "token": "11",
        "file": "/3rd-year/3rd-s2/bsd/pdf/bsd-pdf-11.pdf"
      },
      {
        "token": "12",
        "file": "/3rd-year/3rd-s2/bsd/pdf/bsd-pdf-12.pdf"
      },
      {
        "token": "13",
        "file": "/3rd-year/3rd-s2/bsd/pdf/bsd-pdf-13.pdf"
      },
      {
        "token": "14",
        "file": "/3rd-year/3rd-s2/bsd/pdf/bsd-pdf-14.pdf"
      }
    ]
  },
  "3rd/s2/la": {
    "lecture": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11"
    ],
    "test": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11"
    ],
    "pdf": [
      {
        "token": "1",
        "file": "/3rd-year/3rd-s2/la/pdf/la-1.pdf"
      },
      {
        "token": "2",
        "file": "/3rd-year/3rd-s2/la/pdf/la-2.pdf"
      },
      {
        "token": "3",
        "file": "/3rd-year/3rd-s2/la/pdf/la-3.pdf"
      },
      {
        "token": "4",
        "file": "/3rd-year/3rd-s2/la/pdf/la-4.pdf"
      },
      {
        "token": "5",
        "file": "/3rd-year/3rd-s2/la/pdf/la-5.pdf"
      },
      {
        "token": "6",
        "file": "/3rd-year/3rd-s2/la/pdf/la-6.pdf"
      },
      {
        "token": "7",
        "file": "/3rd-year/3rd-s2/la/pdf/la-7.pdf"
      },
      {
        "token": "8",
        "file": "/3rd-year/3rd-s2/la/pdf/la-8.pdf"
      },
      {
        "token": "9",
        "file": "/3rd-year/3rd-s2/la/pdf/la-9.pdf"
      },
      {
        "token": "10",
        "file": "/3rd-year/3rd-s2/la/pdf/la-10.pdf"
      },
      {
        "token": "11",
        "file": "/3rd-year/3rd-s2/la/pdf/la-11.pdf"
      }
    ]
  }
};
