/* Disk discovery → src/lib/content/contentIndex.ts.
   Scans public/content (lecture/test JSON) and public/<base>/pdf (PDFs) per subject and
   regenerates the content index. Run this whenever you add/remove a lecture, test or PDF:
       npm run discover      (or  npm run migrate, which also runs it last)
   Standalone — reads the in-repo src/lib/site-config.ts and the public/ folder only. */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { SITE } from "../../src/lib/site-config";

const PUB = resolve(process.cwd(), "public");
const CONTENT = resolve(PUB, "content");

const list = (dir: string): string[] => { try { return readdirSync(dir); } catch { return []; } };
const exists = (p: string) => { try { return statSync(p).isDirectory(); } catch { return false; } };
const tokenSort = (a: string, b: string) => (parseFloat(a) || 0) - (parseFloat(b) || 0) || a.localeCompare(b);

function subjectBase(year: (typeof SITE.years)[number], sem: { id: string; folder: string | null }, sub: { id: string; base: string | null }): string {
  if (sub.base) return sub.base.replace(/\/+$/, "");
  const yf = year.folder || year.id + "-year";
  const sf = sem.folder || year.id + "-" + sem.id;
  return `${yf}/${sf}/${sub.id}`;
}

type PdfItem = { token: string; file: string };
const index: Record<string, { lecture: string[]; test: string[]; pdf: PdfItem[] }> = {};

for (const year of SITE.years)
  for (const sem of year.semesters)
    for (const sub of sem.subjects) {
      const key = `${year.id}/${sem.id}/${sub.id}`;
      const cdir = resolve(CONTENT, year.id, sem.id, sub.id);
      const lecture = list(resolve(cdir, "lecture")).filter((f) => f.endsWith(".json")).map((f) => f.replace(/\.json$/, "")).sort(tokenSort);
      const test = list(resolve(cdir, "test")).filter((f) => f.endsWith(".json")).map((f) => f.replace(/\.json$/, "")).sort(tokenSort);

      const base = subjectBase(year, sem, sub);
      const pdfDir = resolve(PUB, base, "pdf");
      const pdf: PdfItem[] = exists(pdfDir)
        ? list(pdfDir)
            .filter((f) => f.toLowerCase().endsWith(".pdf"))
            .map((f) => ({ token: (f.match(/-([\d-]+)\.pdf$/i) || [])[1] || f.replace(/\.pdf$/i, ""), file: `/${base}/pdf/${f}` }))
            .sort((a, b) => tokenSort(a.token, b.token))
        : [];

      if (lecture.length || test.length || pdf.length) index[key] = { lecture, test, pdf };
    }

const out = `/* AUTO-GENERATED by tools/migrate/discover.ts — DO NOT EDIT BY HAND.
   Disk-discovery result (which lectures/tests/PDFs exist). Re-run \`npm run discover\`. */

export type Token = number | string;
export type PdfItem = { token: Token; file: string };
export type SubjectContent = { lecture: Token[]; test: Token[]; pdf: PdfItem[] };
/** key = \`\${yearId}/\${semId}/\${subId}\` */
export type ContentIndex = Record<string, SubjectContent>;

export const CONTENT_INDEX: ContentIndex = ${JSON.stringify(index, null, 2)};
`;

writeFileSync(resolve(process.cwd(), "src", "lib", "content", "contentIndex.ts"), out);

const subj = Object.keys(index).length;
const lec = Object.values(index).reduce((n, s) => n + s.lecture.length, 0);
const tst = Object.values(index).reduce((n, s) => n + s.test.length, 0);
const pdfs = Object.values(index).reduce((n, s) => n + s.pdf.length, 0);
console.log(`Discovered ${subj} subjects with content: ${lec} lectures, ${tst} tests, ${pdfs} PDFs.`);
